# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmdx < Formula
  desc "Task runner. It provides useful help messages and supports interactive prompts and validation of arguments
"
  homepage "https://github.com/suzuki-shunsuke/cmdx"
  version "1.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/cmdx/releases/download/v1.6.1/cmdx_darwin_amd64.tar.gz"
      sha256 "7f777d9c1e2574294ea0d7c04cabadf3735b91f630f8fb1f74b2c74aec27a521"

      def install
        bin.install "cmdx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/cmdx/releases/download/v1.6.1/cmdx_linux_amd64.tar.gz"
      sha256 "38cf6710909e69c732df8cacac95c53989642736b197f9c40eb71484768f25c8"

      def install
        bin.install "cmdx"
      end
    end
  end

  test do
    system "#{bin}/cmdx --version"
  end
end
